services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./apps/backend/data:/app/apps/backend/data
    ports:
      - '3030:3000'
      - '4230:4200'
    environment:
      - DATABASE_PATH=/app/apps/backend/data/db.sqlite
      - PORT=3000
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: apps/backend/package.json
          action: rebuild
        - path: apps/portal/package.json
          action: rebuild
        - path: packages/shared/package.json
          action: rebuild

volumes:
  node_modules:
