services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./apps/backend/data:/app/apps/backend/data
    ports:
      - '3030:3000'
      - '4230:4200'
    environment:
      - DATABASE_PATH=/app/apps/backend/data/db.sqlite
      - PORT=3000
    develop:
      watch:
        - path: apps/backend/src
          action: sync
          target: /app/apps/backend/src
        - path: apps/portal/src
          action: sync
          target: /app/apps/portal/src
        - path: apps/portal/public
          action: sync
          target: /app/apps/portal/public
        - path: apps/portal/angular.json
          action: sync+restart
          target: /app/apps/portal/angular.json
        - path: packages/shared/src
          action: sync+restart
          target: /app/packages/shared/src
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: apps/backend/package.json
          action: rebuild
        - path: apps/portal/package.json
          action: rebuild
        - path: packages/shared/package.json
          action: rebuild
